### ISSUE TITLE
Section links not working

### ISSUE THREAD

**Issue by gkristic** [VividCortex/docs#99]
The links I get from section headers don't take me directly to it if pasted on a new tab. Here's one case:

```
http://docs.vividcortex.com/getting-started/installing/#Installing-For-Amazon-RDS-For-PostgreSQL
```

But the `Installing-For-Amazon-RDS-For-PostgreSQL` identifier doesn't exist in the page, so using that URL I land at the top of the page. I see from source that the identifier is instead:

```
installing-for-amazon-rds-for-postgresql:3cef5cab5612f8cc3d40c6e13331783b
```

**Comment by gkristic** [comment]
Ping @mtrias.

**Comment by mtrias** [comment]
This happened before in #54.

We should create tests for this to prevent this from happening again.

**Comment by mtrias** [comment]
@Andertech mind taking a look into this?

**Comment by Andertech** [comment]
Sure @mtrias, I think this might be a Hugo's configuration issue and might be related it's recent migration. I'll make sure to ping you when I fix it.

**Comment by Andertech** [comment]
This is fixed && deployed $now @gkristic @mtrias I'm closing this.

**Comment by gkristic** [comment]
Still not fixed. Now we're not including the big identifier in the anchor point, but links you get from here still don't direct you to the appropriate section due to case mismatch. For instance, if I copy from the page I get:

```
https://docs.vividcortex.com/getting-started/privileges/#Monitoring-Without-SUPERUSER-Privileges
```

But that lands at the top of the page. The correct address is:

```
https://docs.vividcortex.com/getting-started/privileges/#monitoring-without-superuser-privileges
```

**Comment by Andertech** [comment]
got it working yesterday @gkristic
